### ISSUE TITLE
expiry is not working correctly.

### ISSUE THREAD

**Issue by chrisLeeTW** [tzsk/otp#100]
This demo code should be false in the end, but it's true in real life.

```
Psy Shell v0.10.4 (PHP 7.4.12 — cli) by Justin Hileman
>>> use Tzsk\Otp\Facades\Otp;
>>> $code = Otp::digits(8)->expiry(0.1)->generate('1,2,3');
=> "31619297"
>>> sleep(10);
=> 0
>>> Otp::digits(8)->expiry(0.1)->check($code, '1,2,3');
=> true
>>> 
```

used version : 5.0.1

**Comment by chrisLeeTW** [comment]
```
    public function check($code, $key): bool
    {
        $secret = $this->store->get($this->keyFor($key));
        if (empty($secret)) {
            return false;
        }

        if ($code == $this->calculate($secret)) {
            return true;
        }

        $factor = ($this->time - floor($this->expiry / 2)) / $this->expiry;

        return $code == $this->calculate($secret, $factor);
    }
``` 

I think this line `if ($code == $this->calculate($secret)) {` may be the problem.
Maybe this is right conditional expressions ?
`if ($this->expiry == 0 && $code == $this->calculate($secret)) {`

**Comment by tzsk** [comment]
@chrisLeeTW Awesome catch, looks like you already have a solution. Would you like to contribute a PR? I'll fix if you're not comfortable with that.

**Comment by tzsk** [comment]
@chrisLeeTW Wait. I don't think the `expiry()` method accepts a floating-point value. It tries to cast it to an integer.
```
$minutes = (int) $expiry;

// That means...
(int) 0.1 = 0;

// Then if it finds 0 to be the expiry value then it defaults to 10 min.
```

Closing the issue. Feel free to comment back.

**Comment by chrisLeeTW** [comment]
@tzsk thanks for clarification. Although I do have the need for expiry in seconds.

And after some reading for source code,

```
$ttl = DateInterval::createFromDateString("{$this->time} seconds");
$this->store->put($this->keyFor($key), $secret, $ttl);
```

It seems make `$ttl =  $this->expiry` is more reasonable for cache expiration and storage usage efficiency.

May I know are there any reasons for using `$this->time` as ttl ?

**Comment by tzsk** [comment]
@chrisLeeTW 

Generally OTPs that are being used in any platform have more than a minute of expiration. So it is easier to provide minutes than Seconds.

We can change it but that will cause a breaking change. Maybe for Laravel 9 I can look at revamping that. If received enough requests of making it seconds instead of mins.
