### ISSUE TITLE
Delete used otp

### ISSUE THREAD

**Issue by bonabrian** [tzsk/otp#36]
Please make if otp has used, that delete it.
Thank you

**Comment by tzsk** [comment]
@bonabrian It never stores the OTP anywhere.

**Comment by bonabrian** [comment]
But if the code is already used, the code can be reused.
And thank you, for your response

**Comment by mssyogi** [comment]
@tzsk @bonabrian  I am also facing this issue, I am able to use the used OTP again and again.
Is there any function which we can use to refresh the OTP?

**Comment by tzsk** [comment]
@mssyogi @bonabrian As I'm seeing more and more people running into this issue.

I'm planning to fix it in the nect release. In one or two days. Thanks for reporting.

**Comment by tzsk** [comment]
@mssyogi @bonabrian 

Please update to the latest `v4.0.0` version to get the latest benefits:

### Added
- Unique OTP every time
- Forget OTP feature
- New `otp()` helper

Please test it fully and let me know if you find any issues.
